# Site settings
title: Jonathan Gabel
email: "hello-@-jonathangabel.com"
safe-email: "hello @ jonathangabel.com"
description: > # this means to ignore newlines until "baseurl:"
  The website of Jonathan Gabel. Catalogues of projects, musings, and arcane thoughts.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jonathangabel.com" # the base hostname & protocol for your site
twitter_username: acousticRobot
github_username:  acousticRobot

# Build settings
markdown: kramdown

exclude: [utilities, lib]

kramdown:
  input: GFM
  syntax_highlighter: rouge

# available on local network
host: 0.0.0.0

sass:
  sass_dir: css

collections:
  cv:
    output: false
  links:
    output: false
  projects:
    output: false
  artworks:
    output: true


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: jonathan
      comments: true
      permalink: /:year/:title/
  -
    scope:
      path: ""
      type: "pages"
    values:
      comments: false
  -
    scope:
      path: "toki-pona"
      type: "pages"
    values:
      sub_nav: true
      sub_nav_term_for: "lesson"
      url_up: /toki-pona/
  -
    scope:
      path: ""
      type: "artworks"
    values:
      layout: artwork
      artist: self
      sub_nav: true
      sub_nav_term_for: "artwork"
      url_up: /artworks/
      permalink: /artworks/:path/
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: post
      author: jonathan
      comments: true
      permalink: /:year/:title/

