# Site settings
title: Jonathan Gabel
email: "hello-@-jonathangabel.com"
safe-email: "hello @ jonathangabel.com"
description: > # this means to ignore newlines until "baseurl:"
  The website of Jonathan Gabel. Lists of projects, musings,
  and catalogues of arcane thoughts.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jonathangabel.com" # the base hostname & protocol for your site
twitter_username: acousticRobot
github_username:  acousticRobot

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# available on local network
host: 0.0.0.0

permalink: /:year/:title/

sass:
  sass_dir: css

collections:
  cv:
    output: false
  links:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: jonathan
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      author: jonathan
      comments: false
