# Site settings
title: Jonathan Gabel
email: "hello[@]jonathangabel.com"
description: > # this means to ignore newlines until "baseurl:"
  The website of Jonathan Gabel. Lists of projects, musings,
  and catalogues of arcane thoughts.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jonathangabel.com" # the base hostname & protocol for your site
twitter_username: acousticrobot
github_username:  josankapo

# Build settings
markdown: kramdown
# available on local network
host: 0.0.0.0

permalink: /blog/:year/:title/
